spring:
  application:
    name: tanzu-java-web-app
  config:
    import: optional:configserver:http://spring-config-server.default.svc.cluster.local
  cloud:
    compatibility-verifier:
      enabled: true
  boot:
    admin:
      client:
        url: http://spring-boot-admin.default.svc.cluster.local
        instance:
          service-base-url: http://${spring.application.name}.${NAMESPACE}.${DOMAIN}
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: "./logs/application.log" 
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"


