spring:
  application:
    name: tanzu-java-web-app
  config:
    import: optional:configserver:http://spring-config-server.default.svc.cluster.local
  cloud:
    compatibility-verifier:
      enabled: true

configfrom: "YAML config (application.yml)"